# Generated by Django 4.2.30 on 2026-06-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logauditoria',
            name='ip',
        ),
    ]
